language: python
os: linux
dist: xenial
python: 
  - "3.6"
  - "3.7"
sudo: required
install:
  - pip install -r requirements/dev.txt
  - pip install -e .
script:
  - python -c "from fpe.functions import id_;print(id_('AAAAAAAAAA'))"
  - pytest -v --hypothesis-show-statistics
