language: python
os: linux
dist: xenial
python:
  - "3.6"
  - "3.8"
sudo: required
install:
  - pip install -r requirements/dev.txt
  - pip install -e .
script:
  - pytest -v --hypothesis-show-statistics --cov=fpe
after_success:
  - coveralls
